name: lint_Changed_Files

on:
  workflow_dispatch:  
  push:
    paths:
      - 'project1/**'
  
jobs:
  lint-proj1:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project1
    steps:
    - uses: actions/checkout@v2.4.2
    - name: Use Node.js 
      uses: actions/setup-node@v3.3.0
    - run: npm run lint:script
