name: project1_test

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.2
    - name: Use Node.js 
      uses: actions/setup-node@v3.3.0
    - run: npm ci  
    - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
