name: project1_test
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'project1/**'
  pull_request:
    paths-ignore:
      - 'project1/**'
      
jobs:
  test-proj1:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required proj1" '
