name: project1_test

on:
  workflow_dispatch:
  push:
    paths:
      - 'project1/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project1
    steps:
    - uses: actions/checkout@v2.4.2
    - name: Use Node.js 
      uses: actions/setup-node@v3.3.0
    - run: npm install
    - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
